export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS"
export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE"

export const GET_USER_DETAIL_REQUEST = "GET_USER_DETAIL_REQUEST"
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS"
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE"

export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"

export const GET_ITEM_DETAIL_REQUEST = "GET_ITEM_DETAIL_REQUEST"
export const GET_ITEM_DETAILS_SUCCESS = "GET_ITEM_DETAILS_SUCCESS"
export const GET_ITEM_DETAIL_FAILURE = "GET_ITEM_DETAIL_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"

export const EMPTY_CART_REQUEST = "EMPTY_CART_REQUEST"
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS"
export const EMPTY_CART_FAILURE = "EMPTY_CART_FAILURE"

